const options: { [key: string]: any[] } = {
    DirectoryRecordType: [
        'PATIENT',
        'STUDY',
        'SERIES',
        'IMAGE',
        'RT DOSE',
        'RT STRUCTURE SET',
        'RT PLAN',
        'RT TREAT RECORD',
        'PRESENTATION',
        'WAVEFORM',
        'SR DOCUMENT',
        'KEY OBJECT DOC',
        'SPECTROSCOPY',
        'RAW DATA',
        'REGISTRATION',
        'FIDUCIAL',
        'HANGING PROTOCOL',
        'ENCAP DOC',
        'HL7 STRUC DOC',
        'VALUE MAP',
        'STEREOMETRIC',
        'PALETTE',
        'IMPLANT',
        'IMPLANT GROUP',
        'IMPLANT ASSY',
        'MEASUREMENT',
        'SURFACE',
        'SURFACE SCAN',
        'TRACT',
        'ASSESSMENT',
        'PRIVATE'
    ],
    MappingResource: ['DCMR', 'SDM'],
    ContextGroupExtensionFlag: ['Y', 'N'],
    PatientSex: ['M', 'F', 'O'],
    Laterality: ['R', 'L', 'U', 'B', ''],
    ImageLaterality: ['R', 'L', 'U', 'B', ''],
    PhotometricInterpretation: [
        'MONOCHROME1',
        'MONOCHROME2',
        'PALETTE COLOR',
        'RGB',
        'HSV',
        'ARGB',
        'CMYK',
        'YBR_FULL',
        'YBR_FULL_422',
        'YBR_PARTIAL_422',
        'YBR_PARTIAL_420',
        'YBR_ICT',
        'YBR_RCT'
    ],
    BurnedInAnnotation: ['YES', 'NO'],
    RecognizableVisualFeatures: ['YES', 'NO'],
    MeasurementFunctions: ['PHOTOMETER', 'COLORIMETER', 'ILLUMINOMETER'],
    DisplayFunctionType: [
        'GSDF',
        'CIELAB',
        'GAMMA',
        'LINEAR',
        'LOG10',
        'SRGB',
        'USER_DEFINED'
    ],
    WhitePointFlag: ['YES', 'NO'],
    AmbientLightValueSource: ['DEFAULT', 'MEASURED', 'PROVIDED'],
    MeasuredCharacteristics: [
        'UNIFORMITY',
        'LUMINANCE',
        'CHROMATICITY',
        'ILLUMINANCE'
    ],
    TestResult: ['PASS', 'FAIL', 'SKIP'],
    TestImageValidation: ['MATCHED', 'UNMATCHED'],
    InputReadinessState: ['INCOMPLETE', 'UNAVAILABLE', 'READY'],
    RelationshipType: [
        'CONTAINS',
        'HAS PROPERTIES',
        'HAS OBS CONTEXT',
        'HAS ACQ CONTEXT',
        'INFERRED FROM',
        'SELECTED FROM',
        'HAS CONCEPT MOD'
    ],
    ValueType: [
        'TEXT',
        'NUM',
        'CODE',
        'DATE',
        'TIME',
        'DATETIME',
        'UIDREF',
        'PNAME',
        'COMPOSITE',
        'IMAGE',
        'WAVEFORM',
        'SCOORD',
        'SCOORD3D',
        'TCOORD',
        'CONTAINER'
    ],
    ContinuityOfContent: ['SEPARATE', 'CONTINUOUS'],
    ParticipationType: ['SOURCE', 'ENT', 'ATTEST'],
    TemporalRangeType: ['POINT', 'MULTIPOINT', 'SEGMENT', 'MULTISEGMENT', 'BEGIN', 'END'],
    CompletionFlag: ['PARTIAL', 'COMPLETE'],
    VerificationFlag: ['UNVERIFIED', 'VERIFIED'],
    PreliminaryFlag: ['PRELIMINARY', 'FINAL'],
    SubstanceAdministrationApproval: ['APPROVED', 'WARNING', 'CONTRA_INDICATED'],
    PixelOriginInterpretation: ['FRAME', 'VOLUME'],
    SurfaceProcessing: ['YES', 'NO'],
    FiniteVolume: ['YES', 'NO', 'UNKNOWN'],
    Manifold: ['YES', 'NO', 'UNKNOWN'],
    ImplantType: ['ORIGINAL', 'DERIVED'],
    GraphicType: ['POINT', 'MULTIPOINT', 'POLYLINE', 'POLYGON', 'CIRCLE', 'ELLIPSE', 'ELLIPSOID'],
    FrameOfReferenceTransformationMatrixType: [
        'RIGID',
        'RIGID_SCALE',
        'AFFINE'],
    HangingProtocolLevel: [
        'MANUFACTURER',
        'SITE',
        'USER_GROUP',
        'SINGLE_USER'],
    ImageSetSelectorUsageFlag: ['MATCH', 'NO_MATCH'],
    ImageSetSelectorCategory: ['RELATIVE_TIME', 'ABSTRACT_PRIOR'],
    RelativeTimeUnits: [
        'SECONDS',
        'MINUTES',
        'HOURS',
        'DAYS',
        'WEEKS',
        'MONTHS',
        'YEARS'
    ],
    ImageBoxLayoutType: ['TILED', 'STACK', 'CINE', 'PROCESSED', 'SINGLE'],
    ImageBoxScrollDirection: ['VERTICAL', 'HORIZONTAL'],
    ImageBoxSmallScrollType: ['PAGE', 'ROW_COLUMN', 'IMAGE'],
    ImageBoxLargeScrollType: ['PAGE', 'ROW_COLUMN', 'IMAGE'],
    FilterByAttributePresence: ['PRESENT', 'NOT_PRESENT'],
    FilterByOperator: ['RANGE_INCL', 'RANGE_EXCL', 'GREATER_OR_EQUAL', 'LESS_OR_EQUAL', 'GREATER_THAN', 'LESS_THAN', 'MEMBER_OF', 'NOT_MEMBER_OF'],
    ReformattingOperationInitialViewDirection: ['SAGITTAL', 'TRANSVERSE', 'CORONAL', 'OBLIQUE'],
    SortByCategory: ['ALONG_AXIS', 'BY_ACQ_TIME'],
    ProcedureStepState: [
        'SCHEDULED',
        'IN PROGRESS',
        'CANCELED',
        'COMPLETED'
    ],
    ScheduledProcedureStepPriority: ['HIGH', 'MEDIUM', 'LOW'],
    ImplantAssemblyTemplateType: ['ORIGINAL', 'DERIVED'],
    ExclusiveComponentType: ['YES', 'NO'],
    MandatoryComponentType: ['YES', 'NO'],
    ObservationSignificance: ['MAJOR', 'MODERATE', 'MINOR', 'CONSISTENT'],
    MACAlgorithm: ['RIPEMD160', 'MD5', 'SHA1', 'SHA256', 'SHA384', 'SHA512'],
    PrintPriority: ['HIGH', 'MED', 'LOW'],
    MediumType: ['PAPER', 'CLEAR FILM', 'BLUE FILM', 'MAMMO CLEAR FILM', 'MAMMO BLUE FILM'],
    FilmDestination: ['MAGAZINE', 'PROCESSOR', "`BIN_${number}`"],
    ImageDisplayFormat: [
        "['STANDARD', `${number},${number}`]",
        "['ROW', string]",
        "['COL', string]",
        "['SLIDE']",
        "['SUPERSLIDE']",
        "['CUSTOM', `${number}`]"
    ],
    FilmOrientation: ['PORTRAIT', 'LANDSCAPE'],
    FilmSizeID: ['8INX10IN', '8_5INX11IN', '10INX12IN', '10INX14IN', '11INX14IN', '11INX17IN', '14INX14IN', '14INX17IN', '24CMX24CM', '24CMX30CM', 'A4', 'A3'],
    MagnificationType: ['REPLICATE', 'BILINEAR', 'CUBIC', 'NONE'],
    BorderDensity: ['BLACK', 'WHITE'],
    EmptyImageDensity: ['BLACK', 'WHITE'],
    Trim: ['YES', 'NO'],
    Polarity: ['NORMAL', 'REVERSE'],
    RequestedDecimateCropBehavior: ['DECIMATE', 'CROP', 'FAIL'],
    RequestedResolutionID: ['STANDARD', 'HIGH'],
    DecimateCropResult: ['DECIMATE', 'CROP', 'FAIL', 'DEF DECIMATE', 'DEF CROP', 'DEF FAIL'],
    ExecutionStatus: ['PENDING', 'PRINTING', 'DONE', 'FAILURE'],
    ExecutionStatusInfo: ['NORMAL', 'INVALID PAGE DES', 'INSUFFICIENT MEMORY'],
    PrinterStatus: ['NORMAL', 'WARNING', 'FAILURE'],
    LabelUsingInformationExtractedFromInstances: ['YES', 'NO'],
    AllowMediaSplitting: ['YES', 'NO'],
    IncludeNonDICOMObjects: [
        'NO',
        'FOR_PHYSICIAN',
        'FOR_PATIENT',
        'FOR_TEACHING',
        'FOR_RESEARCH'
    ],
    IncludeDisplayApplication: ['YES', 'NO'],
    PreserveCompositeInstancesAfterMediaCreation: ['YES', 'NO'],
    RequestPriority: ['HIGH', 'MED', 'LOW'],
    TreatmentVerificationStatus: ['VERIFIED', 'VERIFIED_OVR', 'NOT_VERIFIED'],
    RTBeamLimitingDeviceType: ['X', 'Y', 'ASYMX', 'ASYMY', 'MLCX', 'MLCY'],
    RadiationType: [
        'PHOTON',
        'ELECTRON',
        'NEUTRON',
        'PROTON',
        'ION'
    ],
    ApplicatorType: [
        'ELECTRON_SQUARE',
        'ELECTRON_RECT',
        'ELECTRON_CIRC',
        'ELECTRON_SHORT',
        'ELECTRON_OPEN',
        'INTRAOPERATIVE',
        'STEREOTACTIC'
    ],
    WedgePosition: ['IN', 'OUT'],
    GantryRotationDirection: ['CW', 'CC', 'NONE'],
    BeamLimitingDeviceRotationDirection: ['CW', 'CC', 'NONE'],
    PatientSupportRotationDirection: ['CW', 'CC', 'NONE'],
    TableTopEccentricRotationDirection: ['CW', 'CC', 'NONE'],
    TableTopPitchRotationDirection: ['CW', 'CC', 'NONE'],
    TableTopRollRotationDirection: ['CW', 'CC', 'NONE'],
    FixationDeviceType: [
        'BITEBLOCK',
        'HEADFRAME',
        'MASK',
        'MOLD',
        'CAST',
        'HEADREST',
        'BREAST_BOARD',
        'BODY_FRAME',
        'VACUUM_MOLD',
        'WHOLE_BODY_POD',
        'RECTAL_BALLOON'
    ],
    ScanMode: ['NONE' , 'UNIFORM' , 'MODULATED' ],
    PatientSupportType: ['TABLE' , 'CHAIR']
}
export default options